indeedeng/proctor

proctor-common/src/main/java/com/indeed/proctor/common/model/TestType.java, proctor-consumer/src/main/java/com/indeed/proctor/consumer/AbstractGroups.java
The `Objects.firstNonNull` method was deprecated in Guava 18.0 and removed in Guava 21.0.
As far as I can tell, this change makes Proctor compatible with projects that use Guava 21.0.
This addresses the same problem as https://github.com/indeedeng/proctor/issues/18 but in a minimal way that should make it easier to merge.
=> Remove uses of Guava methods removed in Guava 21.0

_config.yml
Commented out baseurl argument in the _config.yml file. Testing shows that the site defaults to its own local domain when this isn't specified.
I've tested this on my stage for over a week and everything is running fine. Please use my stage to verify: https://alette-indeed.github.io/proctor-al-fork/
=> Simplifying docs

proctor-maven-plugin/src/main/resources/log4j.properties
Removing log4j.properties as requested in https://github.com/indeedeng/proctor/issues/15
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/indeedeng/proctor/16)
=> remove log4j

docs/codegen.md
- "`AbstractGroups` provides a application-specific meaning to each test and test-bucket." Changed a --> an
- "The following `plugin` element should be added to your application's `pom.xml` ([complete pom.xml example example](https://gist.github.com/parker/c0ea111ff343f58346e0#file-pom-xml)):" Changed complete pom.xml example example --> complete pom.xml example
- "To man manually run the code generator, run the following in a terminal:" Changed man manually --> manually
=> Fix Minor Typos

_config.yml, _layouts/default.html, _layouts/release_notes.html
To load "ind-eng-logo.png" image correctly in the production environment, we need a base URL before the relative path.
In https://opensource.indeedeng.io/proctor, it will be `/proctor`.
=> Add base url to the paths to "ind-eng-logo.png"

pom.xml
It appears everything in the parent POM that is needed is already replicated or overwritten. Since this is now the only project using it (and [common-parent-pom](https://github.com/indeedeng/common-parent-pom) is already archived), we can remove the reference here.
If for some reason, folks disagree with this change, it's also worth noting that the parent should have been [oss-parent-pom](https://github.com/indeedeng/oss-parent-pom) in the first place anyway.
=> Remove parent POM reference

pom.xml
Reverts indeedeng/proctor#58
Because the proctor library failed to publish by this change, I want to revert this for now.
Here is the failed publishing job: https://github.com/indeedeng/maven-publish/actions/runs/1914581045
=> Revert "Remove parent POM reference"

proctor-consumer/src/main/java/com/indeed/proctor/consumer/ProctorConsumerUtils.java, proctor-consumer/src/test/java/com/indeed/proctor/consumer/spring/TestProctorConsumerUtils.java
The previous behavior was to take the first prforceGroups cookie and use that for the forced groups. If multiple different cookies are set across multiple domains, this could result in groups being dropped along the way. The change here is to set the forced groups as the maximal set of all prforceGroups sent with this request.
=> Parse all force groups cookies

proctor-common/src/main/java/com/indeed/proctor/common/ProctorUtils.java, proctor-common/src/test/java/com/indeed/proctor/common/TestProctorUtils.java, proctor-webapp-library/src/test/java/com/indeed/proctor/webapp/jobs/MatrixCheckerTest.java
Original message is not intuitive/descriptive enough.
Example: Allocation range in acme_inline_survey_tst from CompatibilityChecker refers to unknown bucket value(s) [5] with length > 0
Updated message: Application test specification does not contain bucket values: 5,6. Please update the application test specification first
=> PROW-2085: update to more friendly error message when promoting incompatible changes with unknown bucket

proctor-common/src/main/java/com/indeed/proctor/common/TestSpecification.java
Add `@Nullable` annotation for `TestSpecification` class
`description` field can be null (e.g. `proctor-common/src/test/resources/com/indeed/proctor/common/no-context-specification.json` and specification in `proctor-demo` repository)
=> add null annotation for model

proctor-common/src/main/java/com/indeed/proctor/common/model/Payload.java, proctor-common/src/test/java/com/indeed/proctor/common/model/TestPayload.java
In JSON PR #78 missed adding JSON payload type to the precheckStateAllNull() function thus allowing a payload to have type JSON and any other type causing an exception in ProctorUtils at verifyInternallyConsistentDefinition()::1171
```java 
if (p.numFieldsDefined() != 1) {
throw new IncompatibleTestMatrixException("Test " + testName + " from " + matrixSource
+ " has a test bucket payload with multiple types: " + bucket);
}
```
Change allows for future added payload types to be automatically checked.
=> PROW-2306: Fix checking all null state to include JSON payloads

proctor-common/src/main/java/com/indeed/proctor/common/ProctorUtils.java, proctor-common/src/test/java/com/indeed/proctor/common/TestAbstractJsonProctorLoader.java, proctor-common/src/test/java/com/indeed/proctor/common/TestProctorUtils.java, proctor-common/src/test/resources/com/indeed/proctor/common/unrecognized-payload-test-matrix.json
Handle empty payloads to prevent future failures loading test definitions/matrices with unrecognized payload
=> PROW-2306 Handle Empty Payloads in verify test definition

proctor-consumer/src/main/java/com/indeed/proctor/consumer/AbstractGroups.java, proctor-consumer/src/main/java/com/indeed/proctor/consumer/logging/ExposureLogger.java
Add Exposure Logger to AbstractGroups. This logger will be implemented in the consumer(proctor-interal) side. This is part of central exposure dataset project: https://docs.google.com/document/d/1Yjn8j_P2b7yJIXKVCIU7yO1G9sSpXdeDUVCAmVqOLds/edit
=> EEX-95 Add Exposure Logger to AbstractGroups

proctor-common/src/main/java/com/indeed/proctor/common/ProctorUtils.java, proctor-common/src/main/java/com/indeed/proctor/common/RuleEvaluator.java, proctor-common/src/main/java/com/indeed/proctor/common/RuleVerifyUtils.java, proctor-common/src/test/java/com/indeed/proctor/common/TestProctorUtils.java, proctor-common/src/test/java/com/indeed/proctor/common/TestStandardTestChooser.java
Validate rules are not empty with no heap allocations. Fast-track constant rules evaluation with no heap allocations.
=> PROC-1265: Optimize out allocs in rule validation

proctor-common/src/main/java/com/indeed/proctor/common/dynamic/MetaTagsFilter.java, proctor-common/src/main/java/com/indeed/proctor/common/dynamic/TestNamePatternFilter.java, proctor-common/src/main/java/com/indeed/proctor/common/dynamic/TestNamePrefixFilter.java, proctor-common/src/main/java/com/indeed/proctor/common/model/ConsumableTestDefinition.java, proctor-common/src/test/java/com/indeed/proctor/common/dynamic/TestMetaTagsFilter.java, proctor-common/src/test/java/com/indeed/proctor/common/dynamic/TestTestNamePatternFilter.java, proctor-common/src/test/java/com/indeed/proctor/common/dynamic/TestTestNamePrefixFilter.java
Add isDynamic flag to ConsumableTestDefinition. This will enable us to exclude dynamic tests in exposure logging to reduce the data volume and avoid over logging
=> EEX-149 Add isDynamic flag to ConsumableTestDefinition

proctor-common/src/main/java/com/indeed/proctor/common/model/ConsumableTestDefinition.java
Add a hasLogged flag in ConsumableTestDefinition to track whether a test has logged or not. This can prevent over logging.
=> EEX-153 add a hasLogged flag in ConsumableTestDefinition

proctor-common/src/main/java/com/indeed/proctor/common/ProctorResult.java, proctor-common/src/main/java/com/indeed/proctor/common/model/ConsumableTestDefinition.java
1. Remove hasLogged flag in ConsumableTestDefinition
2. Add Hashset To ProctorResult
=> EEX-153 add hashset to ProctorResult to keep track logged tests

proctor-common/src/main/java/com/indeed/proctor/common/Proctor.java, proctor-common/src/main/java/com/indeed/proctor/common/UnitlessTestChooser.java, proctor-common/src/test/java/com/indeed/proctor/common/TestProctor.java
Case where a test has multiple rules with missingExperimentalUnit and !missingExperimentalUnit and null identifier was being not handled correctly due to misunderstanding on null identifier case.
=> PROC-1346: Handle Unitless Allocation Edge case

proctor-consumer/src/main/java/com/indeed/proctor/consumer/AbstractGroupsManager.java, proctor-consumer/src/main/java/com/indeed/proctor/consumer/logging/ExposureLogger.java
We have moved ExposureLogger to AbstractGroups. The code inside AbstractGroupsManager is no longer needed
=> EEX-148 Clean up ExposureLogger in AbstractGroupsManager

proctor-common/src/main/java/com/indeed/proctor/common/ProctorRuleFunctions.java, proctor-common/src/main/java/com/indeed/proctor/common/RuleEvaluator.java, proctor-common/src/main/java/com/indeed/proctor/common/el/NodeHunter.java, proctor-common/src/main/java/com/indeed/proctor/common/el/PartialExpressionBuilder.java, proctor-common/src/test/java/com/indeed/proctor/common/TestRuleEvaluator.java
Re-implemented [113](https://github.com/indeedeng/proctor/pull/113) to add support for rule filtering for partial contexts.
=> MPEN-145: Added partial matching
